var quotes = ['No hay futuro sin memoria colectiva.',
	'No hay futuro sin cuerpos libres.',
	'No hay futuro sin redes libres.',
	'No hay futuro sin comunidades vivas.',
	'No hay futuro sin tecnologías libres.',
	'No hay futuro sin amistades verdaderas.',
	'No hay futuro sin caminatas a la montaña.',
	'No hay futuro sin movimiento feminista.',
	'No hay futuro sin redes distribuidas.',
	'No hay futuro sin palabra clara.',
	'No hay futuro sin autodefensas.',
	'No hay futuro sin inteligencia colectiva.',
	'No hay futuro sin tecnomagia.',
	'No hay futuro sin combate.',
	'No hay futuro sin narrativas distribuidas.',
	'No hay futuro sin legítima defensa.',
	'No hay futuro sin autonomía tecnológica.',
	'No hay futuro sin tecnologías ancestrales.',
	'No hay futuro sin lenguas ancestrales.',
	'No hay futuro sin complicidad.',
	'No hay futuro sin carnalas de la suerte.',
	'No hay futuro sin periodismo libre.',
	'No hay futuro sin (re)escrituras comprometidas.',
	'No hay futuro sin desapego.',
	'No hay futuro sin co(i)nspiración.',
	'No hay futuro sin ecosistemas de cultura libre.',
	'No hay futuro sin esperanza colectiva.',
	'No hay futuro sin sincronicidad.',
	'No hay futuro sin redes de confianza.',
	'No hay futuro sin semillas.',
	'No hay futuro sin preguntas.',
	'No hay futuro sin riesgo.',
	'No hay futuro sin caída libre.',
	'No hay futuro sin saltos cuánticos.',
	'No hay futuro sin mudanza.',
	'No hay futuro sin interdependencias sanas.',
	'No hay futuro sin dudas.',
	'No hay futuro sin vacío.',
	'No hay futuro sin resiliencia plena.',
	'No hay futuro sin un nuevo error en el sistema.',
	'No hay futuro sin redes de rebeldía.',
	'No hay futuro sin compañeras de viaje.',
	'No hay futuro sin buenas noticias.',
	'No hay futuro sin guaridas.',
	'No hay futuro sin intentos.',
	'No hay futuro sin escribir colectivamente.',
	'No hay futuro sin soñar colectivamente.',
	'No hay futuro sin ruptura.',
	'No hay futuro sin soñar en voz alta.',
	'No hay futuro sin organización de base.',
	'No hay futuro sin conjuros.',
	'No hay futuro sin develaciones.',
	'No hay futuro sin ganas.',
	'No hay futuro sin transbordos.',
	'No hay futuro sin torrents.',
	'No hay futuro sin humildad.',
	'No hay futuro sin redes afectivas sanas.',
	'No hay futuro sin honestidad.',
	'No hay futuro sin radios comunitarias.',
	'No hay futuro sin amigas.',
	'No hay futuro sin chocolate en agua.',
	'No hay futuro sin defensorxs del territorio.',
	'No hay futuro sin afectos interespecie.',
	'No hay futuro sin confianza.',
	'No hay futuro sin salud espiritual',
	'No hay futuro sin conversación.',
		'No hay futuro sin provocación.',
	'No hay futuro sin restauración.',
	'No hay futuro sin pausa.',
	'No hay futuro sin complicidad interespecie.',
	'No hay futuro sin aborto seguro.',
	'No hay futuro sin aborto seguro.',
	'No hay futuro sin circuitos de confianza.',
	'No hay futuro sin refugios nómadas.',
	'No hay futuro sin refugios nómadas.',
	'No hay futuro sin interdependencias consentidas.',
	'No hay futuro sin memoria feminista.',
	'No hay futuro sin memoria radical.',
	'No hay futuro sin cuidados colectivos permanentes.',
	'No hay futuro sin mujeres lesbianas, bisexuales, intersexuales, trans y no binarias organizadas contra la misoginia y el capital.',
]


function newQuote () {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
		document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];

}